# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  #timeout: 5m
  timeout: 5m
  issues-exit-code: 1
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
# output configuration options
output:
  # See the dedicated "output" documentation section.
  sort-results: true
  sort-order:
    - severity

# All available settings of specific linters.
#linters-settings:
  # See the dedicated "linters-settings" documentation section.
  #option: value
linters:
  # See the dedicated "linters" documentation section.
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    #- depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - fatcontext
    #- forbidigo
    #- forcetypeassert
    #- funlen
    #- gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    #- gofmt
    #- gofumpt
    - goheader
    #- goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    #- noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    #- whitespace
    - wrapcheck
    #- wsl
    - zerologlint
#issues:
  # See the dedicated "issues" documentation section.
  #option: value
#severity:
  # See the dedicated "severity" documentation section.
  #option: value